In [ ]:
import numpy as np

In [ ]:
my_list = [1,2,3,4,5,6,7,8]

In [ ]:
a=np.array(my_list)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
b=a[:3]
b

array([1, 2, 3])

In [ ]:
b[0]=88
b

array([88,  2,  3])

In [ ]:
a

array([88,  2,  3,  4,  5,  6,  7,  8])

In [ ]:
c=a.copy()
c[1]=22
c

array([88, 22,  3,  4,  5,  6,  7,  8])

In [ ]:
a

array([88,  2,  3,  4,  5,  6,  7,  8])

In [ ]:
type(c)

numpy.ndarray

In [ ]:
a.shape

(8,)

In [ ]:
a[-1]

8

In [ ]:
a[::-1]

array([ 8,  7,  6,  5,  4,  3,  2, 88])

In [ ]:
b = np.array([[1,2,3], [6,7,8]])
b

array([[1, 2, 3],
       [6, 7, 8]])

In [ ]:
b[1,1] = 77

In [ ]:
b[:,1]

array([ 2, 77])

In [ ]:
b[:,1]=99

In [ ]:
b

array([[ 1, 99,  3],
       [ 6, 99,  8]])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full((3,3),9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [ ]:
np.empty((3,3))

array([[4.64734762e-310, 2.16443571e-312, 2.29175545e-312],
       [8.48798317e-313, 1.08221785e-312, 1.08221785e-312],
       [9.33678148e-313, 8.70018275e-313, 0.00000000e+000]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.arange(5, 60, 3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53,
       56, 59])

In [ ]:
np.linspace(2, 10, 5)

array([ 2.,  4.,  6.,  8., 10.])

In [ ]:
np.random.rand(3,3)

array([[0.33717832, 0.90582345, 0.70752098],
       [0.35573968, 0.75011183, 0.49640133],
       [0.66519086, 0.28371987, 0.06699643]])

In [ ]:
np.random.randn(3,3)

array([[-0.10252852, -0.40542049, -1.76228604],
       [ 0.13112849, -0.0447159 , -0.15661721],
       [ 1.16441461,  0.39678236, -0.10063258]])

In [ ]:
np.random.randint(5, 10)

6

In [ ]:
np.random.randint(5, 10, size=(3,3))

array([[7, 9, 7],
       [5, 9, 6],
       [8, 7, 6]])

In [ ]:
z = np.random.randint(2,15, size=(5,3))
z

array([[ 7,  8,  4],
       [ 2,  7,  9],
       [ 3, 14,  3],
       [10,  5, 11],
       [11, 12, 12]])

In [ ]:
z.shape

(5, 3)

In [ ]:
z.size

15

In [ ]:
z=z.reshape(3,5) # size'ının çarpanları olmak zorunda.
z

array([[ 7,  8,  4,  2,  7],
       [ 9,  3, 14,  3, 10],
       [ 5, 11, 11, 12, 12]])

In [ ]:
z=z.reshape(-1,5)
z

array([[ 7,  8,  4,  2,  7],
       [ 9,  3, 14,  3, 10],
       [ 5, 11, 11, 12, 12]])

In [ ]:
z

array([[ 7,  8,  4,  2,  7],
       [ 9,  3, 14,  3, 10],
       [ 5, 11, 11, 12, 12]])

In [ ]:
z=z.ravel()  # ravel tek dize haline getirir.
z

array([ 7,  8,  4,  2,  7,  9,  3, 14,  3, 10,  5, 11, 11, 12, 12])

In [ ]:
z.max()

14

In [ ]:
z.min()

2

In [ ]:
z.argmax()

7

In [ ]:
z.argmin()

3

In [ ]:
my_arr = np.array([0,1,2,3,4,5,6,7,8,9]).reshape(5,2)
my_arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
my_arr_1 = np.array([0,1,2,3,4,5,6,7,8,9]).reshape(5,2)
my_arr_1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
my_con = np.concatenate([my_arr, my_arr_1])
my_con

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9],
       [0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
my_con = np.concatenate([my_arr, my_arr_1], axis=1)
my_con

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5],
       [6, 7, 6, 7],
       [8, 9, 8, 9]])

**INDEXING AND SLICING**

In [ ]:
my_con

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5],
       [6, 7, 6, 7],
       [8, 9, 8, 9]])

In [ ]:
my_con[1,[2,3]]

array([2, 3])

In [ ]:
my_con[[3,1],2]

array([6, 2])

In [ ]:
my_con[0:2,1:3]

array([[1, 0],
       [3, 2]])

In [ ]:
my_con[:,[0,3]]

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

**STACKING**

In [ ]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
b

array([[5, 6],
       [7, 8]])

In [ ]:
x=np.stack((a,b)) # tuple olarak yazman lazım, yoksa çalışmaz

In [ ]:
x.ndim

3

In [ ]:
x.shape

(2, 2, 2)

In [ ]:
y = np.hstack((a,b))
y

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
y = np.vstack((a,b))

In [ ]:
array_1 = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]])
array_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
bigger_than_5 = array_1 > 5
bigger_than_5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
array_1[bigger_than_5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [ ]:
array_1[array_1<5]

array([1, 2, 3, 4])

In [ ]:
array_1[(array_1<10) & (array_1>3)] # çoklu filtreleme

array([4, 5, 6, 7, 8, 9])

In [ ]:
array_1[(array_1>10) | (array_1<3)]

array([ 1,  2, 11, 12])

In [ ]:
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
y

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.power(x,2)

array([[[ 1,  4],
        [ 9, 16]],

       [[25, 36],
        [49, 64]]])

In [ ]:
np.sqrt(np.power(x,2))

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [ ]:
np.log(x)

array([[[0.        , 0.69314718],
        [1.09861229, 1.38629436]],

       [[1.60943791, 1.79175947],
        [1.94591015, 2.07944154]]])

In [ ]:
np.exp(x)

array([[[2.71828183e+00, 7.38905610e+00],
        [2.00855369e+01, 5.45981500e+01]],

       [[1.48413159e+02, 4.03428793e+02],
        [1.09663316e+03, 2.98095799e+03]]])

In [ ]:
import pandas as pd

In [ ]:
my_list = [1,2,3,4,5,6,7,8]
a = np.array(my_list)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
pd.Series(my_list)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [ ]:
labels = ['X','y','z', 'h']
my_list = [5, 10, 15, 20]
arr = np.array([25, 50, 75, 100])
d = {'a': 10, 'b': 20, 'c': 30, 'd':40}

In [ ]:
pd.Series(my_list, index=labels) # index yerine harfleri yazmış olduk.

X     5
y    10
z    15
h    20
dtype: int64

In [ ]:
pd.Series(arr)

0     25
1     50
2     75
3    100
dtype: int64

In [ ]:
pd.Series(d)

a    10
b    20
c    30
d    40
dtype: int64

In [ ]:
mix_data = [7, "dog", False, np.arange]
pd.Series(mix_data)

0                             7
1                           dog
2                         False
3    <built-in function arange>
dtype: object

In [ ]:
ser = pd.Series([5,10,15,20,25,30], index = ['USA', 'Germany','France', 'UK','Turkey','Greece'])
ser

USA         5
Germany    10
France     15
UK         20
Turkey     25
Greece     30
dtype: int64

In [ ]:
ser.sort_values()

USA         5
Germany    10
France     15
UK         20
Turkey     25
Greece     30
dtype: int64

In [ ]:
ser.sort_index()

France     15
Germany    10
Greece     30
Turkey     25
UK         20
USA         5
dtype: int64

In [ ]:
"Holland" in ser

False

In [ ]:
ser.isin([25])

USA        False
Germany    False
France     False
UK         False
Turkey      True
Greece     False
dtype: bool

In [ ]:
ser.keys()

Index(['USA', 'Germany', 'France', 'UK', 'Turkey', 'Greece'], dtype='object')

In [ ]:
ser.items

<bound method Series.items of USA         5
Germany    10
France     15
UK         20
Turkey     25
Greece     30
dtype: int64>

In [ ]:
for key, value in ser.items():
  print(key, value)

USA 5
Germany 10
France 15
UK 20
Turkey 25
Greece 30


In [ ]:
m = np.arange(1,30, 2).reshape((3,5))
m

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29]])

In [ ]:
df = pd.DataFrame(m, columns=["col1", "col2", "col3", "col4", "col5"])
df

col1  col2  col3  col4  col5
0     1     3     5     7     9
1    11    13    15    17    19
2    21    23    25    27    29

In [ ]:
df.head(2)

col1  col2  col3  col4  col5
0     1     3     5     7     9
1    11    13    15    17    19

In [ ]:
df.tail(2)

col1  col2  col3  col4  col5
1    11    13    15    17    19
2    21    23    25    27    29

In [ ]:
df.sample(2) # rastgele 2 tanesini getirir.