<a href="https://colab.research.google.com/github/dilaraozcerit/python-project/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [1]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [2]:
np.arange(5,26,5)

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [3]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [4]:
a = np.ones((4,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### 5. Make all the values of the array above 7

In [5]:
a[::] = 7
a

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

#### 6. Create same array above with full method

In [6]:
np.full([4, 4], 7, dtype = int)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [7]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [8]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [9]:
np.linspace(0, 24, num=25).reshape(5,5)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

#### 10. Create 5 random number with numpy

In [10]:
np.random.randn(5)

array([-1.17352193, -0.59809876,  1.30422317,  0.37783057, -0.94454257])

#### 11. Create random normal distributed 5x5 array

In [11]:
np.random.randn(25)

array([ 1.22055385,  0.93257413,  0.76846331,  0.6617353 ,  1.49545774,
       -0.78722622, -1.21748393, -0.79302203,  0.0188809 ,  1.15664939,
        0.65813727, -0.19825522, -0.62862218, -0.51939049, -0.40622517,
       -1.2414445 , -0.22841705,  0.58088339,  1.28542393,  0.27229084,
       -0.20545877, -0.88178713,  0.5828244 , -0.76215024, -1.99831825])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [12]:
np.random.randint(20,50, size=(3,4))

array([[31, 27, 46, 33],
       [46, 34, 47, 46],
       [49, 28, 23, 45]])

#### 13. Reshape the array below with shape 6x8

In [13]:
ranarr = np.random.randint(0, 60, 48)

In [14]:
ranarr.reshape(6,8)

array([[19, 20, 39, 29, 25, 32, 27, 52],
       [55, 38, 44, 23, 30, 42, 50, 51],
       [10, 22, 55,  5, 59, 40, 16, 56],
       [30, 14, 24, 45, 18, 20, 21,  2],
       [48, 19, 41, 58, 40, 41, 10, 53],
       [30, 42, 42, 33, 26,  4, 55, 19]])

In [16]:
ranarr.reshape(-1)

array([19, 20, 39, 29, 25, 32, 27, 52, 55, 38, 44, 23, 30, 42, 50, 51, 10,
       22, 55,  5, 59, 40, 16, 56, 30, 14, 24, 45, 18, 20, 21,  2, 48, 19,
       41, 58, 40, 41, 10, 53, 30, 42, 42, 33, 26,  4, 55, 19])

## Numpy Indexing and Selection


In [18]:
arr = np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [19]:
arr[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [20]:
arr[0:, 0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [96]:
arr[1,0:4:2]

array([ 5, 77])

#### 17.Assign 77 to every cell in 3rd column.

In [22]:
arr[0:,2] = 77
arr

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 1st row 0 column, 3th row 2nd column.

In [97]:
arr[1,0:4:2]

array([ 5, 77])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [98]:
arr[1::2,::2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [24]:
a = arr[arr<10] 
a

array([1, 2, 4, 5, 6, 8, 9])

In [25]:
b = arr[arr>12]
b

array([77, 77, 77, 13, 14, 77, 16])

In [26]:
a + b

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [100]:
(a+b).std()

29.700546274093877

#### 22. Get the sum of second column from array above

In [101]:
arr

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [102]:
arr[:,1].sum()

32

#### 23. Get the median,mean and std of 3rd column from array above

In [107]:
arr1 = np.arange(1,17).reshape(4,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [115]:
np.median(arr1[:,2])

9.0

In [118]:
arr1[:,2].mean()

9.0

In [120]:
arr1[:,2].std()

4.47213595499958

# Pandas Section

In [34]:
import pandas as pd

**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [35]:
df = pd.read_csv('Salaries.csv')
df.head(5)

Id       EmployeeName  ...         Agency  Status
0   1     NATHANIEL FORD  ...  San Francisco     NaN
1   2       GARY JIMENEZ  ...  San Francisco     NaN
2   3     ALBERT PARDINI  ...  San Francisco     NaN
3   4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4   5    PATRICK GARDNER  ...  San Francisco     NaN

[5 rows x 13 columns]

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [37]:
df.describe()


Id        BasePay  ...  Notes  Status
count  148654.000000  148045.000000  ...    0.0     0.0
mean    74327.500000   66325.448841  ...    NaN     NaN
std     42912.857795   42764.635495  ...    NaN     NaN
min         1.000000    -166.010000  ...    NaN     NaN
25%     37164.250000   33588.200000  ...    NaN     NaN
50%     74327.500000   65007.450000  ...    NaN     NaN
75%    111490.750000   94691.050000  ...    NaN     NaN
max    148654.000000  319275.010000  ...    NaN     NaN

[8 rows x 10 columns]

**How many different year value are there**

In [38]:
df["Year"].unique()

array([2011, 2012, 2013, 2014])

**Print out max and avg Totalpay**

In [39]:
#max
df["TotalPay"].max()

567595.43

In [40]:
#avg
avg = df["TotalPay"].mean()
avg

74768.321971703

**How many records are there which have TotalPay bigger than avg TotalPay**

In [41]:
len(df[ df["TotalPay"] > avg])

69489

**How much does ALBERT PARDINI make (including benefits)?**

In [94]:
df["TotalPayBenefits"][df["EmployeeName"] == "ALBERT PARDINI"]

2    335279.91
Name: TotalPayBenefits, dtype: float64

**Who is lowest paid person**

In [42]:
df[["TotalPay"]].min

<bound method DataFrame.min of          TotalPay
0       567595.43
1       538909.28
2       335279.91
3       332343.61
4       326373.19
...           ...
148649       0.00
148650       0.00
148651       0.00
148652       0.00
148653    -618.13

[148654 rows x 1 columns]>

**What are the unique Jobs in dataset?**

In [43]:
df["JobTitle"].unique

<bound method Series.unique of 0         GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
1                        CAPTAIN III (POLICE DEPARTMENT)
2                        CAPTAIN III (POLICE DEPARTMENT)
3                   WIRE ROPE CABLE MAINTENANCE MECHANIC
4           DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)
                               ...                      
148649                                         Custodian
148650                                      Not provided
148651                                      Not provided
148652                                      Not provided
148653                        Counselor, Log Cabin Ranch
Name: JobTitle, Length: 148654, dtype: object>

**List 3 least common Jobs**

In [74]:
df["JobTitle"].value_counts().tail(3)

ASSISTANT INDUSTRIAL HYGIENIST    1
ASPHALT PLANT SUPERVISOR I        1
AUDIOLOGIST                       1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012**

In [79]:
len( df[ (df.Year == 2012) & ( df.TotalPayBenefits > df.TotalPayBenefits.mean() )])

20366

**How many people have the word Manager in their job title?**

In [93]:
#use apply function here

def job_t(title):
  if "MANAGER" in title.upper():
    return True
  else:
    return False

sum(df["JobTitle"].apply(lambda x: job_t(x)))

4110

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [73]:
sal_new = df.iloc[:, [0,1,2,7,8]]
sal_new

Id       EmployeeName  ...   TotalPay  TotalPayBenefits
0            1     NATHANIEL FORD  ...  567595.43         567595.43
1            2       GARY JIMENEZ  ...  538909.28         538909.28
2            3     ALBERT PARDINI  ...  335279.91         335279.91
3            4  CHRISTOPHER CHONG  ...  332343.61         332343.61
4            5    PATRICK GARDNER  ...  326373.19         326373.19
...        ...                ...  ...        ...               ...
148649  148650      Roy I Tillery  ...       0.00              0.00
148650  148651       Not provided  ...       0.00              0.00
148651  148652       Not provided  ...       0.00              0.00
148652  148653       Not provided  ...       0.00              0.00
148653  148654          Joe Lopez  ...    -618.13           -618.13

[148654 rows x 5 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [62]:
sal_new = df.loc[:,["EmployeeName","JobTitle","TotalPay","TotalPayBenefits"]] 
sal_new

EmployeeName  ... TotalPayBenefits
0          NATHANIEL FORD  ...        567595.43
1            GARY JIMENEZ  ...        538909.28
2          ALBERT PARDINI  ...        335279.91
3       CHRISTOPHER CHONG  ...        332343.61
4         PATRICK GARDNER  ...        326373.19
...                   ...  ...              ...
148649      Roy I Tillery  ...             0.00
148650       Not provided  ...             0.00
148651       Not provided  ...             0.00
148652       Not provided  ...             0.00
148653          Joe Lopez  ...          -618.13

[148654 rows x 4 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [47]:
df[(df.TotalPayBenefits > df.TotalPayBenefits.min()) & ( df.TotalPayBenefits < df.TotalPayBenefits.mean())][["EmployeeName"]]

EmployeeName
10806          KWE LEE
10807   MIGUEL CARO JR
10808    JOANNE MORRIS
10809    LAYLA WELBORN
10810          LE BANH
...                ...
148648     Leon Walker
148649   Roy I Tillery
148650    Not provided
148651    Not provided
148652    Not provided

[75649 rows x 1 columns]