<a href="https://colab.research.google.com/github/dilaraozcerit/python-project/blob/main/numpy_studying_26_09_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [13]:
a = np.array([1,2,3], dtype="int32")
a

array([1, 2, 3], dtype=int32)

In [4]:
b = np.array([[9.0, 8.0,7.0],[6.0,5.0,4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [5]:
a.ndim

1

In [7]:
b.shape # get shape

(2, 3)

In [9]:
a.dtype # get type

dtype('int64')

In [14]:
a.itemsize # get size


8

In [15]:
b.itemsize

8

In [11]:
a.size # get total size

3

**Accessing / Changing specific elements, rows, columns, etc**


In [16]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [17]:
# Get a specific element [r,c]
a[1,5]

13

In [18]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [23]:
# [startindex:endindex:stepsize]

a[0, 1:-1:2]

array([2, 4, 6])

In [25]:
a[1,5] = 20
print(a)



[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [26]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [27]:
b = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])
b


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [28]:
# Get specified element (work outside in)
b[0,1,1]

4

In [29]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [30]:
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

**Initializing Different Types of Arrays**

In [31]:
# All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [35]:
np.zeros((5,4,5)) # (num of table, num of row, num of column)

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [36]:
# All 1s matrix
np.ones((4,2,2), dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [37]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [42]:
# Any other number ( full_like )
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [43]:
np.full_like(b, 4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [44]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.50441612, 0.94014512],
       [0.31729802, 0.98969374],
       [0.39967477, 0.66914603],
       [0.03437513, 0.59335903]])

In [45]:
np.random.rand(4,2,4)

array([[[3.61047451e-01, 7.80147074e-01, 6.54965843e-01, 9.99158921e-01],
        [2.60716594e-01, 7.21812623e-02, 7.86937393e-01, 8.46172811e-01]],

       [[9.42157580e-01, 5.43738615e-02, 6.02656217e-01, 4.31867331e-01],
        [9.62915693e-02, 2.19659632e-01, 7.65875893e-01, 8.62067507e-01]],

       [[1.53720035e-01, 8.53123447e-03, 9.98650839e-01, 7.56382221e-01],
        [1.71475489e-01, 4.81323131e-01, 6.01524040e-01, 2.13094589e-01]],

       [[7.08267315e-01, 2.58183253e-01, 5.13043897e-01, 6.18099473e-01],
        [5.63843248e-01, 5.26227863e-04, 1.56503226e-01, 9.65019471e-01]]])

In [47]:
# Random Integer Values
np.random.randint(7, size=(3,3))

array([[0, 5, 6],
       [6, 4, 2],
       [0, 2, 1]])

In [50]:
np.random.randint(-4,8, size=(3,3)) # will print the number between -4 and 8.

array([[ 4,  4,  6],
       [-2,  1, -1],
       [-3, -3, -1]])

In [52]:
# The identify matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [63]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0) # by adding "axis=0" we mean vertical -row- to the below. "axis=1" means horizontal -column- to the right.
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [64]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=1) # by adding "axis=0" we mean vertical -row- to the below. "axis=1" means horizontal -column- to the right.
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [54]:
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


TASK

In [75]:
output = np.ones((5,5))
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [78]:
output[1:4, 1:4] = 0
output[2,2] = 9
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

*TASK INSTRUCTOR SOLUTION*

In [86]:
output = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
output[1:4,1:4] = z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

*Be careful when copying!!*

In [87]:
a = np.array([1,2,3])
b = a
b[0] = 100

print(a)

[100   2   3]


In [88]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


*Mathematics*

In [98]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [99]:
a + 2

array([3, 4, 5, 6])

In [102]:
a*2

array([2, 4, 6, 8])

In [103]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [104]:
a ** 2

array([ 1,  4,  9, 16])

In [105]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

*Linear Algebra*

In [107]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [109]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

*Statistics*

In [110]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
np.min(stats)

1

In [113]:
np.max(stats)

6

In [114]:
np.max(stats, axis=1)

array([3, 6])

In [115]:
np.sum(stats)

21

In [116]:
np.sum(stats, axis=0) # add up the elements of each columns. 1+4 , 2+5 , 3+6

array([5, 7, 9])

*Reorganizing Arrays*

In [119]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)


[[1 2 3 4]
 [5 6 7 8]]


In [120]:

after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [122]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [126]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1)
print(h2)

np.hstack((h1,h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

*Boolean Masking and Advanced Indexing*

In [129]:
a = np.array([1,2,3,4,5,6])

In [130]:
a[a > 3]

array([4, 5, 6])

In [132]:
# You can index with a list in NumPY
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [133]:
np.any(a > 5, axis = 0)

True

In [134]:
np.all(a > 5, axis = 0)

False

In [137]:
np.all((a > -5) & (a < 100))

True

*TASK*

In [139]:
arr = np.arange(1, 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [149]:
arr = arr.reshape(6,5)

In [150]:
arr[2:4, 0:2]

array([[11, 12],
       [16, 17]])