In [ ]:
import numpy as np
np.__version__


'1.19.5'

In [ ]:
my_list = [1, 2, 3, 4, 5]
type(my_list)

list

In [ ]:
my_array = np.array([6, 7, 8, 9, 0])
my_array

array([6, 7, 8, 9, 0])

In [ ]:
type(my_array)

numpy.ndarray

In [ ]:
a = [1,2,3,4]
b = [5,6,7,8]
AsumB = []
for i in range(len(a)):
  AsumB.append(a[i] + b[i])

AsumB

[6, 8, 10, 12]

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a + b

array([ 6,  8, 10, 12])

In [ ]:
a*b

array([ 5, 12, 21, 32])

In [ ]:
a.size

4

In [ ]:
a.shape # kaç boyutluysa o kadar rakam çıkacak.

(4,)

In [ ]:
a.ndim # boyutuna baktık

1

In [ ]:
a.dtype # 32 bit 4 byte

dtype('int64')

In [ ]:
a.itemsize

8

In [ ]:
a1 = np.array([[1,2,3,4],[1,2,3,4],[2,3,4,5]])
b1 = np.array([[2,3,4,5],[1,2,4,5],[1,2,3,4]])

In [ ]:
a1.size

12

In [ ]:
a1

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [2, 3, 4, 5]])

In [ ]:
a1.shape

(3, 4)

In [ ]:
a1.itemsize

8

In [ ]:
a1 + b1

array([[3, 5, 7, 9],
       [2, 4, 7, 9],
       [3, 5, 7, 9]])

In [ ]:
a3 = np.array([[[1,2,3,4],[1,2,3,4],[2,3,4,5]], [[1,2,3,4],[1,2,3,4],[2,3,4,5]]] )
a3


array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [2, 3, 4, 5]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [2, 3, 4, 5]]])

In [ ]:
a3.shape

(2, 3, 4)

In [ ]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [ ]:
np.arange(-4, 6)

array([-4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [ ]:
np.arange(-4,6,3)

array([-4, -1,  2,  5])

In [ ]:
np.linspace(1, 10) #start da stop da dahil.

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [ ]:
np.linspace(1, 10, dtype = int)

array([ 1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,
        4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  7,
        7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10])

In [ ]:
np.linspace(0,10,25, dtype=bool)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [ ]:
np.zeros(5) # hepsi 0dan oluşan arrayler...

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5,3), dtype = int) # int yapmazsak float alırdı.

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.zeros((5,3), dtype = bool) 

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
np.ones((2,4)) # hepsi 1'den oluşan arrayler...

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones((2,4))*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
np.ones((2,4))/0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [ ]:
np.full(4, "sonsuz" )

array(['sonsuz', 'sonsuz', 'sonsuz', 'sonsuz'], dtype='<U6')

In [ ]:
np.full((3, 32, 32),355)

array([[[355, 355, 355, ..., 355, 355, 355],
        [355, 355, 355, ..., 355, 355, 355],
        [355, 355, 355, ..., 355, 355, 355],
        ...,
        [355, 355, 355, ..., 355, 355, 355],
        [355, 355, 355, ..., 355, 355, 355],
        [355, 355, 355, ..., 355, 355, 355]],

       [[355, 355, 355, ..., 355, 355, 355],
        [355, 355, 355, ..., 355, 355, 355],
        [355, 355, 355, ..., 355, 355, 355],
        ...,
        [355, 355, 355, ..., 355, 355, 355],
        [355, 355, 355, ..., 355, 355, 355],
        [355, 355, 355, ..., 355, 355, 355]],

       [[355, 355, 355, ..., 355, 355, 355],
        [355, 355, 355, ..., 355, 355, 355],
        [355, 355, 355, ..., 355, 355, 355],
        ...,
        [355, 355, 355, ..., 355, 355, 355],
        [355, 355, 355, ..., 355, 355, 355],
        [355, 355, 355, ..., 355, 355, 355]]])

In [ ]:
import matplotlib.pyplot as plt
%mathplotlib inline

UsageError: Line magic function `%mathplotlib` not found.


In [ ]:
a = np.full((32, 32, 3), 255, dtype=int)
a[:,:,0] = 200 # red
a[:,:,1] = 120 # green
a[:,:,2] = 200 # blue
 # herbiri pikselleri ifade ediyor
plt.imshow(a)

In [ ]:
b = np.arange(36)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [ ]:
b.shape

(36,)

In [ ]:
b.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
b.reshape(12, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35]])

In [ ]:
b.size # size fonksiyonu toplam eleman sayısını verir.

36

In [ ]:
b.reshape(3,3,4) # çarpımlarının 36ya eşit olması lazım, yoksa error. 36, 1 de olabilir.

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [ ]:
c = np.array([20, 21, 22, 23, 24, 25, 26, 27,28, 29, 30, 31, 32, 33, 34, 35, 0, 1,  2,  3, 4,  5,  6,  7])
c

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,  0,
        1,  2,  3,  4,  5,  6,  7])

In [ ]:
c.max()

35

In [ ]:
c.min()

0

In [ ]:
c.argmax()

15

In [ ]:
c.argmin()

16

In [ ]:
c.sum()

468

In [ ]:
c.size

24