In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
data = [1,3,5,6,7,9]
data

[1, 3, 5, 6, 7, 9]

In [ ]:
pd.DataFrame(data)

0
0  1
1  3
2  5
3  6
4  7
5  9

In [ ]:
pd.DataFrame(data, columns=["col1"]) # dataframe'in her sütunu bir seridir.

col1
0     1
1     3
2     5
3     6
4     7
5     9

In [ ]:
pd.Series(data) # series ve dataframe farkı, dataframde column vardır. seriesin sütunları artmaz, dataframe'in artar.

0    1
1    3
2    5
3    6
4    7
5    9
dtype: int64

In [ ]:
data2 = np.arange(1, 24, 2).reshape(3,4)
data2

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [ ]:
pd.DataFrame(data2, columns=["col1", "col2", "col3", "col4"]) # yukardaki yapının aynısı. index ve column kazanmış hali.


col1  col2  col3  col4
0     1     3     5     7
1     9    11    13    15
2    17    19    21    23

In [ ]:
df = pd.DataFrame(data2, columns=["col1", "col2", "col3", "col4"], index=["a", "b", "c"]) 
df
# indexleri değiştirdik.

col1  col2  col3  col4
a     1     3     5     7
b     9    11    13    15
c    17    19    21    23

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.size # eleman sayısını verir

12

In [ ]:
df.shape

(3, 4)

In [ ]:
df.ndim # dimension(boyutunu) gösterir

2

In [ ]:
df.columns

Index(['col1', 'col2', 'col3', 'col4'], dtype='object')

In [ ]:
df.values

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [ ]:
df.index

Index(['a', 'b', 'c'], dtype='object')

In [ ]:
df.keys() # keys = column

Index(['col1', 'col2', 'col3', 'col4'], dtype='object')

In [ ]:
len(df)

3

In [ ]:
s1 = np.random.randint(2,10, size = 40)
s2 = np.random.randint(30,100, size = 40)
s3 = np.random.randint(100,150, size = 40)

In [ ]:
s1

array([3, 4, 4, 2, 9, 3, 7, 6, 5, 7, 8, 3, 6, 7, 6, 7, 7, 8, 4, 6, 9, 4,
       2, 2, 4, 6, 4, 8, 5, 6, 6, 2, 9, 5, 5, 7, 3, 3, 7, 3])

In [ ]:
myDict = {"var1": s1, "var2": s2, "var3": s3}
myDict

{'var1': array([3, 4, 4, 2, 9, 3, 7, 6, 5, 7, 8, 3, 6, 7, 6, 7, 7, 8, 4, 6, 9, 4,
        2, 2, 4, 6, 4, 8, 5, 6, 6, 2, 9, 5, 5, 7, 3, 3, 7, 3]),
 'var2': array([50, 83, 69, 41, 97, 59, 78, 97, 85, 34, 85, 48, 55, 89, 94, 30, 30,
        89, 68, 53, 66, 51, 86, 83, 66, 43, 36, 95, 30, 54, 74, 81, 69, 57,
        71, 64, 39, 83, 96, 51]),
 'var3': array([146, 106, 115, 133, 117, 124, 121, 121, 126, 110, 108, 135, 128,
        124, 146, 124, 128, 138, 148, 102, 148, 107, 123, 128, 141, 112,
        114, 123, 139, 107, 110, 138, 118, 115, 135, 128, 133, 100, 133,
        115])}

In [ ]:
pd.DataFrame(myDict)

var1  var2  var3
0      3    50   146
1      4    83   106
2      4    69   115
3      2    41   133
4      9    97   117
5      3    59   124
6      7    78   121
7      6    97   121
8      5    85   126
9      7    34   110
10     8    85   108
11     3    48   135
12     6    55   128
13     7    89   124
14     6    94   146
15     7    30   124
16     7    30   128
17     8    89   138
18     4    68   148
19     6    53   102
20     9    66   148
21     4    51   107
22     2    86   123
23     2    83   128
24     4    66   141
25     6    43   112
26     4    36   114
27     8    95   123
28     5    30   139
29     6    54   107
30     6    74   110
31     2    81   138
32     9    69   118
33     5    57   115
34     5    71   135
35     7    64   128
36     3    39   133
37     3    83   100
38     7    96   133
39     3    51   115

In [ ]:
df_dict = pd.DataFrame(myDict)

In [ ]:
df_dict[3:5]

var1  var2  var3
3     2    41   133
4     9    97   117

In [ ]:
df_dict2.index = ["a", "b"]
df_dict2

NameError: ignored

In [ ]:
df_dict2.columns = ["X", "Y", "Z"]
df_dict2

NameError: ignored

In [ ]:
pd.DataFrame(df_dict2.values, index=["c", "d"], )

**Indexing, selection and slicing methods**

In [ ]:
np.random.seed(101)
np.random.randn(5,4)

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [ ]:
"A B C D E".split(" , ")

['A B C D E']

In [ ]:
np.random.seed(101)
df3 = pd.DataFrame(  np.random.randn(5,4),
                   index = ['A', 'B', 'C', 'D', 'E'],
                   columns = 'W X Y Z'.split())
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3["W"]

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [ ]:
df3.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [ ]:
df3[["W"]] # tipi dataframe oldu artık

W
A  2.706850
B  0.651118
C -2.018168
D  0.188695
E  0.190794

In [ ]:
df3[["W", "Y"]]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077
C -2.018168  0.528813
D  0.188695 -0.933237
E  0.190794  2.605967

In [ ]:
df3.loc[:, "W":"Y"]

W         X         Y
A  2.706850  0.628133  0.907969
B  0.651118 -0.319318 -0.848077
C -2.018168  0.740122  0.528813
D  0.188695 -0.758872 -0.933237
E  0.190794  1.978757  2.605967

In [ ]:
df3["X"]

A    0.628133
B   -0.319318
C    0.740122
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [ ]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3["X"] + df3["Y"]**2

A    1.452541
B    0.399917
C    1.019766
D    0.112060
E    8.769823
dtype: float64

In [ ]:
df3.insert

<bound method DataFrame.insert of           W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509>

In [ ]:
df3["Result"] = df3["W"]*df3["X"] + df3["Y"]**2 - df3["Z"]
df3


W         X         Y         Z    Result
A  2.706850  0.628133  0.907969  0.503826  2.020844
B  0.651118 -0.319318 -0.848077  0.605965 -0.094644
C -2.018168  0.740122  0.528813 -0.589001 -0.625047
D  0.188695 -0.758872 -0.933237  0.955057 -0.227320
E  0.190794  1.978757  2.605967  0.683509  6.485092

In [ ]:
df3["Result"] = df3["W"]*df3["X"] + df3["Y"]**2 - df3["Z"].mean()
df3


W         X         Y         Z    Result
A  2.706850  0.628133  0.907969  0.503826  2.092798
B  0.651118 -0.319318 -0.848077  0.605965  0.079450
C -2.018168  0.740122  0.528813 -0.589001 -1.645918
D  0.188695 -0.758872 -0.933237  0.955057  0.295865
E  0.190794  1.978757  2.605967  0.683509  6.736730

In [ ]:
df3["Z"].mean()

0.43187119296667903

In [ ]:
df3["Y"].std()

1.4545158461817913

In [ ]:
df3["Y"].std()

1.4545158461817913

In [ ]:
df3.drop("Result", axis=1) # result sütunumuzu sildik.

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3.drop(["X", "Y"], axis=1) # İki sütun birden düşürdük 

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [ ]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3.drop(["C", "E"], axis=0) # C ve E sütunlarını sildik.

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057

.loc[]

In [ ]:
m=np.random.randint(1,40, size=(8,4))
df4 = pd.DataFrame(m, columns = ["var1","var2","var3",'var4'])
df4

var1  var2  var3  var4
0     8    11    39    10
1    19     8    16     1
2    13    18    12    16
3    34    30    25    37
4    20    36    31    11
5    21    28     9    23
6    27    24    38    23
7    10     3    19    29

In [ ]:
df4.loc[2]

var1    13
var2    18
var3    12
var4    16
Name: 2, dtype: int64

In [ ]:
df4.loc[2:6]

var1  var2  var3  var4
2    13    18    12    16
3    34    30    25    37
4    20    36    31    11
5    21    28     9    23
6    27    24    38    23

In [ ]:
df4.index='a b c d e f g h'.split()
df4

var1  var2  var3  var4
a     8    11    39    10
b    19     8    16     1
c    13    18    12    16
d    34    30    25    37
e    20    36    31    11
f    21    28     9    23
g    27    24    38    23
h    10     3    19    29

In [ ]:
df4.loc["c"]

var1    13
var2    18
var3    12
var4    16
Name: c, dtype: int64

In [ ]:
df4.loc["c":"f"] # c ve f arasını alıyoruz!

var1  var2  var3  var4
c    13    18    12    16
d    34    30    25    37
e    20    36    31    11
f    21    28     9    23

In [ ]:
df4.loc["c":"f", "var1":"var3"]   # var1 ve var3 arasını da alıyoruz..

var1  var2  var3
c    13    18    12
d    34    30    25
e    20    36    31
f    21    28     9

In [ ]:
df4.loc["c":"f"][["var1","var2","var3"]] # bu şekilde de olabilir.

var1  var2  var3
c    13    18    12
d    34    30    25
e    20    36    31
f    21    28     9

.iloc[]

In [ ]:
df4

var1  var2  var3  var4
a     8    11    39    10
b    19     8    16     1
c    13    18    12    16
d    34    30    25    37
e    20    36    31    11
f    21    28     9    23
g    27    24    38    23
h    10     3    19    29

In [ ]:
df4.iloc[1:4, 2:4]

var3  var4
b    16     1
c    12    16
d    25    37

In [ ]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df.iloc[2:4]

col1  col2  col3  col4
c    17    19    21    23

In [ ]:
df3.iloc[:,2:4]

Y         Z
A  0.907969  0.503826
B -0.848077  0.605965
C  0.528813 -0.589001
D -0.933237  0.955057
E  2.605967  0.683509

In [ ]:
df3.iloc[ 1 , 2:]

Y   -0.848077
Z    0.605965
Name: B, dtype: float64

Conditional Selection


In [ ]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3["X"] > 0

A     True
B    False
C     True
D    False
E     True
Name: X, dtype: bool

In [ ]:
df3[ df3["X"] > 0] # conditionladık 

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
C -2.018168  0.740122  0.528813 -0.589001
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3[ (df3["X"] > 0) & (df3["Z"] > 0)] 

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3[ (df3.X > 0) & (df3.Z > 0)] # yukardakinin aynısını gönderdi

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3["X"] > 0

A     True
B    False
C     True
D    False
E     True
Name: X, dtype: bool

In [ ]:
df3[ [True,False,True,False,True]] # index yani len sayısı kadar eleman gönderir

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
C -2.018168  0.740122  0.528813 -0.589001
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3[ df3.Z > 0 ][["W"]] # Z sütünuna göre conditionlayıp W'yi aldık

W
A  2.706850
B  0.651118
D  0.188695
E  0.190794

In [ ]:
df_3 = df3[ df3.Z > 0]
df_3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
( df3[ df3.Z > 0 ]).iloc[2:5,:]

W         X         Y         Z
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509