<a href="https://colab.research.google.com/github/dilaraozcerit/python-project/blob/main/Statistics_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

In [1]:
from scipy import stats

 Import **NumPy**, **SciPy**, and **Pandas**

In [2]:
import numpy as np
import scipy as sp
import pandas as pd

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [3]:
samples = np.random.normal(100,15, 1000)
samples

array([ 95.86190194, 110.47393876, 116.63857545, 107.2324398 ,
        98.19522537, 106.79917246,  99.52084909, 133.03404268,
        92.1747306 ,  99.68476364,  96.25150383, 110.92038668,
        93.6455434 ,  91.48944943, 101.97679008, 110.64315255,
       103.11521015, 111.01250653, 124.63953687, 109.94847594,
        82.84508377,  83.13859666,  84.70828768,  86.52687956,
       112.15786868, 104.28767797, 108.41601431, 122.01608866,
       107.00071595, 102.28496869,  86.03662163, 121.72605352,
       112.11961789,  84.32625266, 128.0983973 , 124.09133354,
       122.51490468,  90.79604485,  94.46087024, 115.42066987,
       106.84849109,  87.74336554, 110.76269579,  99.1549932 ,
       113.09769364,  91.86948804,  63.78942622, 100.25225508,
        83.11115241,  88.05852308,  91.40531213, 113.22041408,
        81.27982616,  99.94309529,  77.84029348, 102.83370041,
        90.36093406,  90.4348189 ,  79.57269287, 127.33152688,
       129.35926336, 101.90491705,  90.07866697, 105.96

Compute the **mean**, **median**, and **mode**

In [4]:
mean = samples.mean()
median = np.median(samples)
mode = stats.mode(samples)

print( mean )
print(median)
print(mode)

100.38094701310257
100.18951000413362
ModeResult(mode=array([56.4045]), count=array([1]))


Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [29]:
min = samples.min()
max = samples.max()
q1 = np.percentile(samples, [25])
q3 = np.percentile(samples, [75])
iqr = stats.iqr(samples)

print(min)
print(max)
print(q1)
print(q3)
print(iqr)

56.40449999949959
156.61366082091183
[91.13890098]
[109.99612091]
18.857219929696413


Compute the **variance** and **standard deviation**

In [6]:
variance = samples.var()
std_dev = samples.std()

print(variance)
print(std_dev)

212.46171821153624
14.576066623459713


Compute the **skewness** and **kurtosis**

In [7]:
from scipy.stats import kurtosis
from scipy.stats import skew

In [8]:
skewness = skew(samples, bias=False)
kurtosis = kurtosis(samples, bias=False)

print(skewness)
print(kurtosis)

0.07802009127843344
0.20315228513347172


## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [9]:
x = np.arange(10, 20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [10]:
y = np.array([1,2,3,4,5,6,7,8,9,10])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [14]:
r = np.corrcoef(x,y)
r

array([[1., 1.],
       [1., 1.]])

## Pandas Correlation Calculation

Run the code below

In [17]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [22]:
r = stats.pearsonr(x, y)
r

(0.758640289091187, 0.010964341301680813)

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [27]:
rho = stats.spearmanr(x, y)
rho

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)

## Seaborn Dataset Tips

Import Seaborn Library

In [24]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [25]:
tips = sns.load_dataset("tips")

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [28]:
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [30]:
tips.corr('pearson')

total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000